//Pokemon names without the hyphen and other info
export const pokemonNameExceptions = [
  { id: 29, name: "Nidoran♀" },
  { id: 32, name: "Nidoran♂" },
  { id: 122, name: "Mr. Mime" },
  { id: 386, name: "Deoxys" },
  { id: 413, name: "Wormadam" },
  { id: 439, name: "Mime Jr." },
  { id: 487, name: "Giratina" },
  { id: 492, name: "Shaymin" },
  { id: 550, name: "Basculin" },
  { id: 555, name: "Darmanitan" },
  { id: 641, name: "Tornadus" },
  { id: 642, name: "Thundurus" },
  { id: 645, name: "Landorus" },
  { id: 647, name: "Keldeo" },
  { id: 648, name: "Meloetta" },
  { id: 678, name: "Meowstic" },
  { id: 681, name: "Aegislash" },
  { id: 710, name: "Pumpkaboo" },
  { id: 711, name: "Gourgeist" },
  { id: 741, name: "Oricorio" },
  { id: 745, name: "Lycanroc" },
  { id: 746, name: "Wishiwashi" },
  { id: 772, name: "Type: Null" },
  { id: 774, name: "Minior" },
  { id: 778, name: "Mimikyu" },
  { id: 785, name: "Tapu Koko" },
  { id: 786, name: "Tapu Lele" },
  { id: 787, name: "Tapu Bulu" },
  { id: 788, name: "Tapu Fini" },
  { id: 849, name: "Toxtricity" },
  { id: 866, name: "Mr. Rime" },
  { id: 875, name: "Eiscue" },
  { id: 876, name: "Indeedee" },
  { id: 888, name: "Zacian" },
  { id: 889, name: "Zamazenta" },
  { id: 892, name: "Urshifu" },
];
